Repository Lubycon/lubycon-ui-kit, pull requests merged in 2020-11, with the labels that each got.

#1 chore: 기본적인 package.json 내용 추가
  package.json
Labels: 🙌 good first issue

#2 chore: UI Kit 빌드 세팅 완료
  .eslintrc.js
  .gitignore
  .npmignore
  .nvmrc
  .prettierignore
  .prettierrc
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  rollup.config.js
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/components/Button/index.tsx
  src/components/Button/style.scss
  src/components/index.scss
  src/components/index.ts
  src/index.css
  src/index.tsx
  src/logo.svg
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/sass/modules/_test.scss
  src/setupTests.ts
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: 🚥 chore

#8 미팅때 논의했던 editorconfig 추가
  .editorconfig
Labels: 🚥 chore

#9 Chore/#3 storybook 설정
  .storybook/main.js
  package.json
  src/components/Button/index.stories.tsx
  yarn.lock
Labels: 🚥 chore

#10 Chore/#4 Github Actions Npm publish
  .github/workflows/npm.yml
Labels: 🚥 chore

#12 chore: 모노레포 세팅
  .eslintrc.js
  .github/workflows/deploy-ui-kit-lib.yml
  .github/workflows/npm.yml
  .gitignore
  .nvmrc
  package.json
  packages/ui-kit/.eslintrc.js
  packages/ui-kit/.npmignore
  packages/ui-kit/.storybook/main.js
  packages/ui-kit/package.json
  packages/ui-kit/rollup.config.js
  packages/ui-kit/src/components/Button/index.stories.tsx
  packages/ui-kit/src/components/Button/index.tsx
  packages/ui-kit/src/components/Button/style.scss
  packages/ui-kit/src/components/index.scss
  packages/ui-kit/src/components/index.ts
  packages/ui-kit/src/sass/modules/_test.scss
  packages/ui-kit/tsconfig.build.json
  packages/ui-kit/tsconfig.json
  services/lubycon-ui-kit-docs/README.md
  services/lubycon-ui-kit-docs/next-env.d.ts
  services/lubycon-ui-kit-docs/package.json
  services/lubycon-ui-kit-docs/pages/about.tsx
  services/lubycon-ui-kit-docs/pages/api/users/index.ts
  services/lubycon-ui-kit-docs/pages/index.tsx
  services/lubycon-ui-kit-docs/pages/users/[id].tsx
  services/lubycon-ui-kit-docs/pages/users/index.tsx
  services/lubycon-ui-kit-docs/src/components/Layout.tsx
  services/lubycon-ui-kit-docs/src/components/List.tsx
  services/lubycon-ui-kit-docs/src/components/ListDetail.tsx
  services/lubycon-ui-kit-docs/src/components/ListItem.tsx
  services/lubycon-ui-kit-docs/src/models/index.ts
  services/lubycon-ui-kit-docs/src/utils/sample-data.ts
  services/lubycon-ui-kit-docs/tsconfig.json
  src/components/index.ts
  tsconfig.build.json
  tsconfig.common.json
  yarn.lock
Labels: 🚥 chore

#20 feat(ui-kit): Text 컴포넌트 디자인 변경
  .github/workflows/publish-storybook.yml
  ui-kit/src/components/Text/index.stories.tsx
  ui-kit/src/components/Text/index.tsx
  ui-kit/src/components/Text/types.ts
  ui-kit/src/sass/utils/_typography.scss
Labels: ✨ enhancement
