Repository Lubycon/lubycon-ui-kit, pull requests merged in 2021-03, with the labels that each got.

#53 feat(ui-kit): Tag 컴포넌트 추가
  ui-kit/src/components/Input/index.tsx
  ui-kit/src/components/Tag/index.tsx
  ui-kit/src/index.ts
  ui-kit/src/sass/components/_Input.scss
  ui-kit/src/sass/components/_Tag.scss
  ui-kit/src/sass/components/_index.scss
  ui-kit/src/stories/Input.stories.tsx
  ui-kit/src/stories/List.stories.tsx
  ui-kit/src/stories/Tag.stories.tsx
Labels: ✨ enhancement

#54 Feat/modal
  ui-kit/src/components/Modal/index.tsx
  ui-kit/src/contexts/Modal.tsx
  ui-kit/src/stories/Modal.stories.tsx
Labels: 🚥 chore

#56 Feat/table re
  ui-kit/src/components/Table/TableBody.tsx
  ui-kit/src/components/Table/TableCell.tsx
  ui-kit/src/components/Table/TableHead.tsx
  ui-kit/src/components/Table/TableRow.tsx
  ui-kit/src/components/Table/index.tsx
  ui-kit/src/index.ts
  ui-kit/src/sass/components/_Table.scss
  ui-kit/src/sass/components/_index.scss
  ui-kit/src/stories/Table.stories.tsx
Labels: ✨ enhancement

#57 feat(ui-kit): Modal 컴포넌트 애니메이션 추가
  ui-kit/src/components/Modal/index.tsx
  ui-kit/src/components/Table/TableCell.tsx
  ui-kit/src/components/Table/TableHead.tsx
  ui-kit/src/components/Table/TableRow.tsx
  ui-kit/src/contexts/Modal.tsx
  ui-kit/src/sass/components/_Modal.scss
  ui-kit/src/stories/Table.stories.tsx
Labels: ✨ enhancement

#58 feat(ui-kit): Tabs 컴포넌트 리팩토링 및 모바일 대응 추가
  ui-kit/src/components/Tabs/TabContext.ts
  ui-kit/src/components/Tabs/TabNav.tsx
  ui-kit/src/components/Tabs/TabNavList.tsx
  ui-kit/src/components/Tabs/TabNode.tsx
  ui-kit/src/components/Tabs/TabPane.tsx
  ui-kit/src/components/Tabs/TabPanelList.tsx
  ui-kit/src/components/Tabs/Tabs.tsx
  ui-kit/src/components/Tabs/TabsContext.ts
  ui-kit/src/components/Tabs/TabsIndicator.tsx
  ui-kit/src/components/Tabs/TabsItem.tsx
  ui-kit/src/components/Tabs/index.ts
  ui-kit/src/components/Tabs/index.tsx
  ui-kit/src/components/Tabs/types.ts
  ui-kit/src/hooks/index.ts
  ui-kit/src/hooks/useCombinedRefs.ts
  ui-kit/src/hooks/useMergedState.ts
  ui-kit/src/hooks/useRefs.ts
  ui-kit/src/index.ts
  ui-kit/src/sass/components/_Tabs.scss
  ui-kit/src/sass/utils/_index.scss
  ui-kit/src/sass/utils/_scrollbar.scss
  ui-kit/src/stories/Tabs.stories.tsx
Labels: ✨ enhancement

#62 feat(docs): UI Kit Docs 페이지 와꾸 추가
  docs/package.json
  docs/pages/_app.tsx
  docs/pages/_document.tsx
  docs/pages/about.tsx
  docs/pages/api/.gitkeep
  docs/pages/api/users/index.ts
  docs/pages/getting-started.ts
  docs/pages/index.ts
  docs/pages/index.tsx
  docs/pages/users/[id].tsx
  docs/pages/users/index.tsx
  docs/src/components/BasicLayout/index.tsx
  docs/src/components/GlobalHeader/index.tsx
  docs/src/components/GlobalSidebar/index.tsx
  docs/src/components/Layout.tsx
  docs/src/components/List.tsx
  docs/src/components/ListDetail.tsx
  docs/src/components/ListItem.tsx
  docs/src/components/PostSection/index.tsx
  docs/src/constants/menu.ts
  docs/src/constants/resources.ts
  docs/src/pages/GettingStartedPage/index.tsx
  docs/src/pages/HomePage/index.tsx
  docs/src/utils/menu.ts
  yarn.lock
Labels: 📄 Docs

#64 chore(docs): static resource 404 떨어지는 이슈 해결
  docs/scripts/deploy.js
Labels: 📄 Docs
