Repository Lubycon/lubycon-ui-kit, pull requests merged in 2021-02, with the labels that each got.

#38 fix(ui-kit): 탭 컴포넌트 타입 깨지는 부분 수정
  ui-kit/src/components/Tabs/TabNavList.tsx
  ui-kit/src/components/Tabs/TabPane.tsx
  ui-kit/src/components/Tabs/Tabs.tsx
  ui-kit/src/hooks/useMergedState.ts
  ui-kit/src/hooks/useRefs.ts
  ui-kit/src/utils/index.ts
  ui-kit/src/utils/toArray.ts
Labels: 🐛 bug

#37 feat(ui-kit): 툴팁 컴포넌트 추가
  ui-kit/src/components/Tooltip/TooltipBody.tsx
  ui-kit/src/components/Tooltip/index.tsx
  ui-kit/src/components/Tooltip/types.ts
  ui-kit/src/components/Tooltip/utils.ts
  ui-kit/src/components/index.ts
  ui-kit/src/sass/components/_Button.scss
  ui-kit/src/sass/components/_Tooltip.scss
  ui-kit/src/sass/components/_index.scss
  ui-kit/src/stories/Tooltip.stories.tsx
  ui-kit/src/utils/dom.ts
Labels: ✨ enhancement

#40 feat(ui-kit): 토스트 포지션 및 스타일 수정
  ui-kit/src/components/Button/index.tsx
  ui-kit/src/components/Text/index.tsx
  ui-kit/src/components/Toast/index.tsx
  ui-kit/src/sass/components/_Toast.scss
  ui-kit/src/stories/Toast.stories.tsx
Labels: ✨ enhancement

#41 feat(ui-kit): 스낵바 컴포넌트 추가
  ui-kit/src/components/LubyconUIKitProvider/index.tsx
  ui-kit/src/components/Snackbar/SnackbarBody.tsx
  ui-kit/src/components/Snackbar/index.tsx
  ui-kit/src/components/index.ts
  ui-kit/src/contexts/Snackbar.tsx
  ui-kit/src/sass/components/_Button.scss
  ui-kit/src/sass/components/_Snackbar.scss
  ui-kit/src/sass/components/_index.scss
  ui-kit/src/stories/Snackbar.stories.tsx
  ui-kit/src/stories/Toast.stories.tsx
Labels: ✨ enhancement

#42 style(ui-kit): 수민님 디자인 피드백 반영
  ui-kit/src/components/Switch/index.tsx
  ui-kit/src/sass/components/_Switch.scss
Labels: 🚥 chore

#39 feat(ui-kit): 카드 컴포넌트 추가
  .eslintrc.js
  ui-kit/src/components/Card/CardContent.tsx
  ui-kit/src/components/Card/CardFooter.tsx
  ui-kit/src/components/Card/CardHeader.tsx
  ui-kit/src/components/Card/CardImageContent.tsx
  ui-kit/src/components/Card/index.tsx
  ui-kit/src/components/index.ts
  ui-kit/src/sass/components/_Card.scss
  ui-kit/src/sass/components/_index.scss
  ui-kit/src/sass/utils/_colors.scss
  ui-kit/src/stories/Card.stories.tsx
Labels: ✨ enhancement

#43 feat(ui-kit): Alert, Container 컴포넌트 추가
  ui-kit/.storybook/preview.js
  ui-kit/src/components/Alert/index.tsx
  ui-kit/src/components/Card/CardImageContent.tsx
  ui-kit/src/components/Container/index.tsx
  ui-kit/src/components/Container/style.scss
  ui-kit/src/components/Grid/Column.tsx
  ui-kit/src/components/Grid/types.ts
  ui-kit/src/components/Icon/index.tsx
  ui-kit/src/components/Text/index.tsx
  ui-kit/src/components/index.ts
  ui-kit/src/constants/colors.ts
  ui-kit/src/sass/components/_Alert.scss
  ui-kit/src/sass/components/_Column.scss
  ui-kit/src/sass/components/_Container.scss
  ui-kit/src/sass/components/_Row.scss
  ui-kit/src/sass/components/_index.scss
  ui-kit/src/sass/utils/_breakpoints.scss
  ui-kit/src/sass/utils/_colors.scss
  ui-kit/src/stories/Alert.stories.tsx
  ui-kit/src/stories/Colors.stories.tsx
  ui-kit/src/stories/Grid.stories.tsx
Labels: ✨ enhancement

#44 refactor(ui-kit): 코드 정리
  ui-kit/.storybook/preview.js
  ui-kit/rollup.config.js
  ui-kit/src/components/Button/index.tsx
  ui-kit/src/components/Checkbox/index.tsx
  ui-kit/src/components/Grid/Column.tsx
  ui-kit/src/components/Grid/Row.tsx
  ui-kit/src/components/Radio/index.tsx
  ui-kit/src/components/Switch/index.tsx
  ui-kit/src/components/Text/index.tsx
  ui-kit/src/components/index.ts
  ui-kit/src/index.ts
  ui-kit/src/sass/components/_Button.scss
  ui-kit/src/sass/components/_Checkbox.scss
  ui-kit/src/sass/components/_Column.scss
  ui-kit/src/sass/components/_Radio.scss
  ui-kit/src/sass/components/_Row.scss
  ui-kit/src/sass/components/_Text.scss
  ui-kit/src/sass/utils/_grid.scss
  ui-kit/src/sass/utils/_typography.scss
  ui-kit/src/stories/Alert.stories.tsx
  ui-kit/src/stories/Button.stories.tsx
  ui-kit/src/stories/Card.stories.tsx
  ui-kit/src/stories/Checkbox.stories.tsx
  ui-kit/src/stories/Colors.stories.tsx
  ui-kit/src/stories/Grid.stories.tsx
  ui-kit/src/stories/Radio.stories.tsx
  ui-kit/src/stories/Selection.stories.tsx
  ui-kit/src/stories/Shadows.stories.tsx
  ui-kit/src/stories/Snackbar.stories.tsx
  ui-kit/src/stories/Switch.stories.tsx
  ui-kit/src/stories/Tabs.stories.tsx
  ui-kit/src/stories/Text.stories.tsx
  ui-kit/src/stories/Toast.stories.tsx
  ui-kit/src/stories/Tooltip.stories.tsx
Labels: 🚥 chore

#46 feat(ui-kit): Input 컴포넌트 추가
  ui-kit/src/components/Input/index.tsx
  ui-kit/src/index.ts
  ui-kit/src/sass/components/_Input.scss
  ui-kit/src/sass/components/_index.scss
  ui-kit/src/stories/Input.stories.tsx
Labels: ✨ enhancement

#45 feat(ui-kit): List, ListItem, ListItemImage 컴포넌트 추가
  ui-kit/package.json
  ui-kit/src/components/List/ListItem.tsx
  ui-kit/src/components/List/ListItemImage.tsx
  ui-kit/src/components/List/index.tsx
  ui-kit/src/index.ts
  ui-kit/src/sass/components/_List.scss
  ui-kit/src/sass/components/_index.scss
  ui-kit/src/sass/utils/_typography.scss
  ui-kit/src/stories/List.stories.tsx
Labels: ✨ enhancement

#49 chore: UPDATE README [skip ci]
  LICENSE
  README.md
Labels: 🚥 chore

#47 feat(ui-kit): Accordion 컴포넌트 추가
  ui-kit/package.json
  ui-kit/src/components/Accordion/index.tsx
  ui-kit/src/hooks/useResizeObserver.ts
  ui-kit/src/index.ts
  ui-kit/src/sass/components/_Accordion.scss
  ui-kit/src/sass/components/_Input.scss
  ui-kit/src/sass/components/_index.scss
  ui-kit/src/stories/Accordion.stories.tsx
  yarn.lock
Labels: ✨ enhancement

#48 feat(ui-kit): ProgressBar 컴포넌트 추가
  ui-kit/src/components/ProgressBar/index.tsx
  ui-kit/src/index.ts
  ui-kit/src/sass/components/_ProgressBar.scss
  ui-kit/src/sass/components/_index.scss
  ui-kit/src/stories/ProgressBar.stories.tsx
Labels: ✨ enhancement

#51 feat(ui-kit): Button 컴포넌트 타입 추가
  ui-kit/src/components/Accordion/index.tsx
  ui-kit/src/components/Alert/index.tsx
  ui-kit/src/components/Button/index.tsx
  ui-kit/src/components/Card/CardImageContent.tsx
  ui-kit/src/components/Input/index.tsx
  ui-kit/src/components/List/ListItem.tsx
  ui-kit/src/components/Snackbar/SnackbarBody.tsx
  ui-kit/src/components/Snackbar/index.tsx
  ui-kit/src/sass/components/_Button.scss
  ui-kit/src/stories/Button.stories.tsx
  ui-kit/src/stories/Toast.stories.tsx
  ui-kit/src/stories/Tooltip.stories.tsx
Labels: ✨ enhancement

#52 chore(ui-kit): 커스텀 도메인을 위한 CNAME 추가
  ui-kit/package.json
  ui-kit/public/CNAME
Labels: 🚥 chore

#50 feat(ui-kit): Modal 컴포넌트 추가
  ui-kit/src/components/LubyconUIKitProvider/index.tsx
  ui-kit/src/components/Modal/ModalBackdrop.tsx
  ui-kit/src/components/Modal/ModalContent.tsx
  ui-kit/src/components/Modal/ModalFooter.tsx
  ui-kit/src/components/Modal/ModalHeader.tsx
  ui-kit/src/components/Modal/ModalWindow.tsx
  ui-kit/src/components/Modal/index.tsx
  ui-kit/src/contexts/Modal.tsx
  ui-kit/src/index.ts
  ui-kit/src/sass/components/_Modal.scss
  ui-kit/src/sass/components/_index.scss
  ui-kit/src/stories/Modal.stories.tsx
Labels: ✨ enhancement
